Default: &defaults
  user: cutsea110
  password: cutsea110
  host: localhost
  port: 5432
  database: Test
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Test_test
  <<: *defaults

Staging:
  database: Test_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Test_production
  poolsize: 100
  <<: *defaults
